/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultGameIdRouteImport } from './routes/result.$gameId'
import { Route as HistoryGameIdRouteImport } from './routes/history.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultGameIdRoute = ResultGameIdRouteImport.update({
  id: '/result/$gameId',
  path: '/result/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryGameIdRoute = HistoryGameIdRouteImport.update({
  id: '/history/$gameId',
  path: '/history/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history/$gameId': typeof HistoryGameIdRoute
  '/result/$gameId': typeof ResultGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history/$gameId': typeof HistoryGameIdRoute
  '/result/$gameId': typeof ResultGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history/$gameId': typeof HistoryGameIdRoute
  '/result/$gameId': typeof ResultGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history/$gameId' | '/result/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history/$gameId' | '/result/$gameId'
  id: '__root__' | '/' | '/history/$gameId' | '/result/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryGameIdRoute: typeof HistoryGameIdRoute
  ResultGameIdRoute: typeof ResultGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$gameId': {
      id: '/result/$gameId'
      path: '/result/$gameId'
      fullPath: '/result/$gameId'
      preLoaderRoute: typeof ResultGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$gameId': {
      id: '/history/$gameId'
      path: '/history/$gameId'
      fullPath: '/history/$gameId'
      preLoaderRoute: typeof HistoryGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryGameIdRoute: HistoryGameIdRoute,
  ResultGameIdRoute: ResultGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
